"""add agency id to users and cases

Revision ID: 1e39221234e2
Revises: ce3cea4b2de7
Create Date: 2026-05-16 12:51:10.565405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e39221234e2'
down_revision: Union[str, Sequence[str], None] = 'ce3cea4b2de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(length=200), nullable=True),
    sa.Column('agency_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.drop_table('Agencies')
    op.add_column('cases', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'agencies', ['agency_id'], ['agency_id'])
    op.drop_column('cases', 'reporting_agency_id')
    op.add_column('users', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'agencies', ['agency_id'], ['agency_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'agency_id')
    op.add_column('cases', sa.Column('reporting_agency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'agency_id')
    op.create_table('Agencies',
    sa.Column('agency_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agency_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('agency_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agency_id', name=op.f('Agencies_pkey'))
    )
    op.drop_table('agencies')
    # ### end Alembic commands ###
