"""initial beacon migration

Revision ID: ce3cea4b2de7
Revises: 
Create Date: 2026-05-16 11:35:57.120047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3cea4b2de7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Timeline of Events_event_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('Activity_Log')
    op.drop_index(op.f('ix_Person_id'), table_name='Person')
    op.drop_table('Person')
    op.drop_table('Alerts')
    op.alter_column('cases', 'case_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cases', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'priority_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'cases', ['case_number'])
    op.create_foreign_key(None, 'cases', 'persons', ['person_id'], ['person_id'])
    op.create_foreign_key(None, 'external_records', 'persons', ['person_id'], ['person_id'])
    op.create_foreign_key(None, 'external_records', 'cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'external_records', type_='foreignkey')
    op.drop_constraint(None, 'external_records', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='unique')
    op.alter_column('cases', 'priority_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('cases', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cases', 'case_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('Alerts',
    sa.Column('alert_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_agency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alert_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('Alerts_pkey'))
    )
    op.create_table('Person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scars', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tattoos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medical_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dna_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_ur', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Person_pkey'))
    )
    op.create_index(op.f('ix_Person_id'), 'Person', ['id'], unique=False)
    op.create_table('Activity_Log',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('Activity_Log_pkey'))
    )
    op.create_table('timeline_events',
    sa.Column('event_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('Timeline of Events_pkey'))
    )
    op.create_index(op.f('ix_Timeline of Events_event_id'), 'timeline_events', ['event_id'], unique=False)
    # ### end Alembic commands ###
